######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 15 22:26:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h vidcap.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp vidcap.cpp
LIBS += -lopencv_core -lopencv_highgui
